### ISSUE TITLE
Error in Magento 2.4.5

### ISSUE THREAD

**Issue by CalzaFino** [TidycodeIT/magento2-meta-robots#1]
Installed the module and the menu shows in the Admin as expected but it breaks completely the front store. This is the error reported in the log:

```
[2022-08-21T06:50:41.138175+00:00] main.CRITICAL: Error: Cannot instantiate interface Tidycode\MetaRobotsTag\Api\SetMetaRobotsInterface in /cache/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /cache/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Tidycode\\MetaRo...', Array)
#1 /cache/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Tidycode\\MetaRo...')
#2 /cache/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Tidycode\\MetaRo...')
#3 /cache/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Tidycode\\MetaRo...')
#4 /cache/vendor/magento/framework/Event/ObserverFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->get('Tidycode\\MetaRo...')
#5 /cache/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Framework\Event\ObserverFactory->get('Tidycode\\MetaRo...')
#6 /cache/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 /cache/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('layout_generate...', Array)
#8 /cache/vendor/magento/framework/View/Layout/Builder.php(134): Magento\Framework\Event\Manager\Proxy->dispatch('layout_generate...', Array)
#9 /cache/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /cache/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /cache/vendor/magento/framework/View/Page/Config.php(227): Magento\Framework\View\Layout\Builder->build()
#12 /cache/vendor/magento/framework/View/Page/Config.php(591): Magento\Framework\View\Page\Config->build()
#13 /cache/vendor/magento/framework/View/Page/Config.php(549): Magento\Framework\View\Page\Config->getElementAttribute('body', 'class')
#14 /cache/vendor/magento/module-catalog/Controller/Category/View.php(246): Magento\Framework\View\Page\Config->addBodyClass('page-products')
#15 /cache/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Category\View->execute()
#16 /cache/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('execute', Array)
#17 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#18 /cache/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(23): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('execute', Array, Array)
#19 /cache/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#20 /cache/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /cache/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', Array)
#22 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /cache/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(32): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /cache/vendor/magento/framework/App/FrontController.php(245): Magento\Catalog\Controller\Category\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /cache/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Magento\Framework\App\Request\Http))
#26 /cache/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Category\View\Interceptor))
#27 /cache/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /cache/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#29 /cache/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /cache/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /cache/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /cache/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /cache/vendor/swissup/module-amp/Plugin/Framework/FrontController.php(48): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /cache/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /cache/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /cache/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /cache/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /cache/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#39 /cache/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#40 {main} [] []
```

**Comment by dadolun95** [comment]
Hello @CalzaFino 
I've tried to replicate the error on a clean magento 2.4.5 instance on warden with these configurations:
ELASTICSEARCH_VERSION=7.16
MARIADB_VERSION=10.4
NODE_VERSION=14
PHP_VERSION=8.1
RABBITMQ_VERSION=3.8
REDIS_VERSION=6.2
VARNISH_VERSION=7.0
And there's no errors on frontend. Judging by the error logged I think is a di problem with the "generated" folder. 
Please try to remove the "generated" folder and execute bin/magento setup:di:compile command and let me know if the error persists.

**Comment by LotsofPixels** [comment]
This is a M2.4.2 on 7.4 I am getting the following random error:
TypeError: Return value of Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity() must be of the type bool, 
null returned in /data/web/application/vendor/tidycode/meta-robots-tag/Model/SetMetaRobots.php:54 Stack trace:

Is there a way to avoid that?
